### ISSUE TITLE
RSS des podcast RadioFrance : absence de lien de téléchargement

### ISSUE THREAD

**Issue by batbast** [tontof/kriss_feed#190]
Bonjour,

kriss_feed n'indique pas le lien vers le podcast (pour téléchargement) dans le cas des flux RSS de RadioFrance.

Voici un exemple avec http://radiofrance-podcast.net/podcast09/rss_11193.xml.

L'image ci-dessous indique le rendu avec kriss_feed (version 7).
![kriss_feed](https://f.cloud.github.com/assets/1963792/401205/c3550dde-a8d2-11e2-8e86-696af5277698.png)

Cette image suivante montre bien la présence du lien de télépchargement, visible depuis l'ouverture du flux dans firefox.
![firefox](https://f.cloud.github.com/assets/1963792/401217/fccccd4a-a8d2-11e2-8ad8-b4ac55ee69af.png)

Merci d'avance (et toutes mes félicitations pour ce fabuleux lecteur RSS).

**Comment by tontof** [comment]
Ça aura été long, mais c'est ajouté
https://github.com/tontof/kriss_feed/commit/3fc964453c6d6c17aed7056ebd9cc80e23281c28
On source you should see something as
```<br><audio controls=""><source src="http://rf.proxycast.org/1174344394057195520/14007-12.06.2016-ITEMA_21007891-1.mp3"></source><a href="http://rf.proxycast.org/1174344394057195520/14007-12.06.2016-ITEMA_21007891-1.mp3">http://rf.proxycast.org/1174344394057195520/14007-12.06.2016-ITEMA_21007891-1.mp3</a></audio>```

**Comment by tontof** [comment]
On https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats
```The MP3 audio format (.mp3, audio/mpeg; distinct from the above MP3 audio in an MP4 container case) is supported in <audio> by Firefox/Firefox for Android/Firefox OS when the operating system provides an MP3 decoder```

**Comment by batbast** [comment]
Merci bien. 
Long ? Je n'avais qu'à corriger moi même ! 

Le 14 juin 2016 09:27:28 GMT+02:00, tontof <notifications@github.com> a écrit :
>Ça aura été long, mais c'est ajouté
>https://github.com/tontof/kriss_feed/commit/3fc964453c6d6c17aed7056ebd9cc80e23281c28
>On source you should see something as
>```<br><audio controls=""><source
>src="http://rf.proxycast.org/1174344394057195520/14007-12.06.2016-ITEMA_21007891-1.mp3"></source><a
>href="http://rf.proxycast.org/1174344394057195520/14007-12.06.2016-ITEMA_21007891-1.mp3">http://rf.proxycast.org/1174344394057195520/14007-12.06.2016-ITEMA_21007891-1.mp3</a></audio>```
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tontof/kriss_feed/issues/190#issuecomment-225800759

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by tontof** [comment]
:-)
