### ISSUE TITLE
anchor "begin of the next item" don't work

### ISSUE THREAD

**Issue by tolima** [tontof/kriss_feed#296]
On my smartphone (htc wlidfire s with Opera) when I mark as read an item, the anchor (the one who put you in the beginning of the next item) don't work.
Not sure if it's a Kriss feed problem but it's annoying to scoll to the top of a BIG article.
Not a big issue. 
Tank you again for KF, you make a great job !

ps: sorry for my title, I haven't found a better one.

**Comment by tolima** [comment]
it works now. Thanks :)

**Comment by tontof** [comment]
great!
