### ISSUE TITLE
Favicons: getFavicon service over it's serving quota

### ISSUE THREAD

**Issue by Metal-Mighty** [tontof/kriss_feed#357]
Hi

I've always had favicons enabled on my Kriss install and since a few months they are not showing anymore. The cause is that the service has been "temporarily over it's service quota". I refresh Kriss multiple times daily and I have never seen my favicons back in the past few months.

I fixed the issue by replacing line 2559
```batchfile
$url = 'http://getfavicon.appspot.com/'.$htmlUrl.'?defaulticon=bluepng';
```
... With one of Google's hidden service originally shared on Google S2
```batchfile
$url = 'http://www.google.com/s2/favicons?domain='.$htmlUrl;
```

The blue planet still shows correctly when there's no favicon to display after that.

**Comment by tontof** [comment]
I modify it
https://github.com/tontof/kriss_feed/commit/3f1eb8fcde87faa270d8f4cb03470caee164e67c
Thanks
