### ISSUE TITLE
[Request] Titre par défaut pour une entrée RSS

### ISSUE THREAD

**Issue by Metal-Mighty** [tontof/kriss_feed#361]
Certains flux RSS n'indiquent pas de titre pour certaines entrées, dépendamment des données de départ. Etant donné qu'aucun titre n'est généré, il n'est pas possible d'accéder directement au lien en question.

Je joins une capture d'écran prenant pour exemple un flux RSS "Blogger" dont certains champs titre ne sont pas renseignés. Le flux RSS en question est [par ici] (https://www.blogger.com/feeds/4332083148473199984/posts/default).

![capture](https://cloud.githubusercontent.com/assets/5247527/9072178/b1fe7bf4-3ac7-11e5-9c62-b692d2b02e97.PNG)

Est-ce qu'il serait possible d'ajouter un titre par défaut dans ce cas de figure?

**Comment by tontof** [comment]
Je vois effectivement le problème que ça pose. Ce n'est pas très compliqué à modifier, je vais essayer de trouver un moment pour modifier ça !

**Comment by tontof** [comment]
J'ai mis à jour. Quand il n'y a pas de titre ça affiche l'url.
exemple : http://tontof.net/feed/?currentHash=WcObEQ

Pour le moment, ce n'est que sur la dev
https://raw.githubusercontent.com/tontof/kriss_feed/master/src/index.php
