### ISSUE TITLE
getfavicon.appspot.com ne renvoie plus de favicon

### ISSUE THREAD

**Issue by Tiwy57** [tontof/kriss_feed#362]
Je viens à peine d'installer Kriss Feed, très bon boulot d'ailleurs :+1: 
Cependant, les favicons (qui sont récupérées par un service tiers) ne s'affichent plus.

En regardant de plus près, effectivement, le site http://getfavicon.appspot.com/ n'a plus l'air de faire le travail (404 apparemment).

Embêtant. 

Je propose, juste au cas où, le service de google qui pourrait éventuellement le remplacer :
`http://s2.googleusercontent.com/s2/favicons?domain_url=`
Avec à la fin l'URL. Le fichier retourné est le favicon du site.
Si la favicon n'est pas trouvée, ça nous renvoie une boule bleue.

Ça marche pas forcément avec tout les sites, notamment ceux qui ont des favicons dans des sous répertoires. 
- Le cas avec le shaarli de sebsauvage : Ça nous renvoie une boule bleue, au lieu de la favicon de Shaarli (et je pensais qu'il aurait cherché à la base du host, le fameux œil, mais loupé !)
  - Pour le coup, la solution c'est un coup de parse_url pour récupérer uniquement le protocole, le hostname, balancer le tout à Google, qui nous renvoie le favicon à la racine du site.

Bon, je sais, on utilise Google ...

**Comment by tontof** [comment]
Salut,

Il y a déjà une version qui fonctionne avec les favicons dans le répertoire src :
https://raw.githubusercontent.com/tontof/kriss_feed/master/src/index.php

Ça fonctionne effectivement avec google

**Comment by Tiwy57** [comment]
Ah, pas vu dans les sources effectivement.
Merci du coup !
