### ISSUE TITLE
Mot de passe sur flux RSS

### ISSUE THREAD

**Issue by cborne** [tontof/kriss_feed#363]
Bonjour

J'accède à un flux RSS privé, j'ai besoin de mettre un login et un mot de passe. Voilà y a plus qu'à coder :)

Cyrille

**Comment by marienfressinaud** [comment]
En principe tu devrais pouvoir y accéder avec http://user:password@exemple.com/?feed-je-sais-pas-quoi ;)

**Comment by cborne** [comment]
tu as laissé tomber Fresh RSS :D ?

**Comment by marienfressinaud** [comment]
Non, je surveille juste Kriss Feed de loin et je réponds aux tickets quand je peux :p

**Comment by tontof** [comment]
Tu confirmes que ça marche Cyrille ?
Merci pour la réponse Marien je ne suis pas sûr que j'aurais pensé à cette solution !

**Comment by cborne** [comment]
je viens de faire le test dans miniflux, ça passe, je pense que dans kriss feed ça doit le faire aussi, je vais faire l'essai. Réponse tardive mais avec Thunderbird qui sent le sapin, je regarde à nouveau les solutions en ligne
