### ISSUE TITLE
Problème de favoris sur smartphone ou tablette

### ISSUE THREAD

**Issue by cborne** [tontof/kriss_feed#367]
Sur smartphone ou tablette, lorsque je mets un lien en favori, ben il ne se met pas en favori. 

Ca serait sympa si tu avais 5 minutes de refaire un peu l'interface smartphone pour avoir des gros boutons pour les doigts boudinés.

**Comment by tontof** [comment]
C'est quel navigateur, quelle version parce que je n'ai aucun problème avec Firefox et le navigateur de base sur Android.

Pour tes gros doigts boudinés, tu peux personnalisés le style en ajoutant un user.css
http://tontof.net/kriss/feed/#style
et mettre ça dedans
```css
@media (max-width: 767px) {
    .item-top > .label,
    .item-shaarli > .label,
    .item-starred > .label,
    .item-mark-as > .label {
        margin: 0 5px;
    }

    .item-title, .label {
        line-height: 44px;
    }

    .label {
        padding: 0 24px !important;
    }
}
```

**Comment by cborne** [comment]
il s'agit de firefox pour android dans sa dernière mouture. Et nous sommes deux à avoir un problème similaire : http://cyrille-borne.com/article2309/une-histoire-de-temps#c1458774422-1

Pour le reste je vais attendre que tu nous fasses une nouvelle release :D

**Comment by tontof** [comment]
Je n'ai pas de dernière mouture sous la main pour tester sur Android mais pour tes gros doigts j'ai fait une nouvelle version 8.1 :-p
https://raw.githubusercontent.com/tontof/kriss_feed/master/index.php
Backup avant au cas où.

**Comment by cborne** [comment]
hummmm j'aime quand tu me parles comme ça, ça donne des envies de te faire coder.

**Comment by cborne** [comment]
c'est franchement mais je pense que tu peux faire encore mieux. Dans le cas des petites résolutions article précédent, article suivant le nombre de page etc n'a pas vraiment de sens. Le "haut" aussi ça fait décaler, une flèche peut être ?

**Comment by tontof** [comment]
J'ai légèrement amélioré parce que ça s'affichait n'importe comment au niveau de la liste des flux
https://github.com/tontof/kriss_feed/commit/c595d59dcf58c3c5643cbe761e05d064cdd92ced

Pour les boutons qui s'affichent (article précédent, nombre de pages, etc.) il y a des options dans la partie configuration pour les masquer. Il suffit de mettre 0 pour « Page » dans « Préférence du menu de pagination de KrISS feed »
Par contre c'est général, ça le supprimera pour la version bureau et mobile, si tu veux que ce ne soit que sur la version mobile, tu n'auras pas d'autres choix que de passer pas un ```user.css``` personnalisé.

Mais sinon je n'ai rien compris à ton message:
« Le "haut" aussi ça fait décaler, une flèche peut être ? »

**Comment by cborne** [comment]
dans le bas d'un article tu as haut - partager - lire - conserver. Sur mon téléphone conserver passe à la ligne d'en dessous.

**Comment by cborne** [comment]
effectivement en passant les 4 derniers paramètres à 0 c'est plus joli en mobile. 

sur l'invite d'accueil nom d'utilisateur chevauche la barre de saisie, pas insupportable mais pas très joli

**Comment by tontof** [comment]
Je pense que c'est pas mal comme ça (boutons + invite d'accueil) :
https://raw.githubusercontent.com/tontof/kriss_feed/master/index.php
Les boutons prennent toute la largeur maintenant, du coup si tu me dis que la taille pose encore problème, je vais devoir te demander des photos

**Comment by cborne** [comment]
Voilà à quoi ça ressemble chez moi. Quand tu fais défiler très vite, pour moi le bouton du haut est gênant car j'ai le doigt qui cache le texte, je ne sais pas si je suis clair. L'idéal en fait serait d'avoir une barre avec les trois boutons ou les quatre qui se baladeraient sur le bas de l'écran en décalé de façon à avoir toujours le titre de l'article en haut en permanence comme c'est le cas actuellement. Je ne sais pas si tu as compris ce que je veux dire.
![screenshot_2016-03-24-13-46-28](https://cloud.githubusercontent.com/assets/3888577/14017384/51785c0c-f1c7-11e5-808a-3e16e28027be.png)

**Comment by tontof** [comment]
Tu as essayé avec les gros boutons ?
https://raw.githubusercontent.com/tontof/kriss_feed/8a9755f16cb282a4270047ea565168ce3fd0bbdf/index.php
Sinon je pense que c'était ça que tu voulais ça
https://raw.githubusercontent.com/tontof/kriss_feed/75d9777e3231b642ee42e1a9678d22f213113238/index.php
Je ne peux pas tester pour voir si ça fonctionne, mais j'ai peur qu'avec l'effet swipe pour lire un article, le scroll horizontal risque de ne pas forcément bien marcher...

**Comment by cborne** [comment]
là dans les deux cas tu me pointes du code, je dois faire quoi ? J'installe l'un puis l'autre ?

**Comment by tontof** [comment]
Ouais tu remplaces juste le index.php
Le premier c'est avec les gros boutons le second c'est avec un défilement horizontal

**Comment by cborne** [comment]
ça c'est gros boutons, ça prend quand même de la place 

![screenshot_2016-03-24-14-25-25](https://cloud.githubusercontent.com/assets/3888577/14018172/83d90b6a-f1cc-11e5-8f82-19c5b15589d7.png)

**Comment by cborne** [comment]
chez moi ça marche plutôt pas mal le défilement vers la droite. Par contre deux choses

si l'url partager n'est pas alimentée peut-on envisager de ne pas afficher le bouton partager. Et si cette solution du défilement vers la droite est retenue, est il possible en version mobile de plus afficher le bouton lire

**Comment by tontof** [comment]
Si tu veux virer les boutons lire et partager, le défilement vers la droite ne servira pas.

Par contre il va falloir que tu le fasses avec un fichier ```user.css``` parce que par défaut je pense que c'est bien de les laisser.
Tu veux les virer en haut et en bas de l'article ou juste en bas ?

**Comment by cborne** [comment]
Pas compris pourquoi le défilement vers la droite ne servira pas. Si je défile vers la droite, ça lit automatiquement je n'ai pas de lire, comme je n'ai pas d'association avec shaarli, je n'ai pas besoin du bouton partager. En fait en faisant défiler vers la droite et en n'ayant pas de shaarli je n'ai besoin que du bouton conserver que je peux garder en haut et en bas qui prendrait toute la largeur de l'écran éventuellement pour faire propre

**Comment by tontof** [comment]
Pour moi défilement vers la droite c'était les boutons qui défilaient alors que toi tu sembles parler du défilement vers la droite pour marquer comme lu.

Mais en gros, toi tu veux la première version avec les gros boutons mais sans les boutons lire et partager.

Pour ça l'idéal c'est d'utiliser un ```user.css``` mais comme tu sembles hésitant sur cette solution, tu peux avoir cet [index.txt](https://github.com/tontof/kriss_feed/files/188000/index.txt)
Il faut renommer en index.php parce que github n'accepte pas les fichiers php.

Le problème c'est qu'avec cet index tu ne pourras plus mettre à jour sans perdre la personnalisation contrairement à un fichier ```user.css``` :-)
qui contiendrait ça :
```css
  .item-shaarli > .label,
  .item-mark-as > .label {
      display: none;
  }
```

**Comment by cborne** [comment]
Le comportement de mon smartphone, si je balaye vers la droite l'article est marqué comme lu avec le code que tu m'as fourni. Par contre si tu ne fais pas le défilement vers la droite, j'ai besoin du bouton lire. 

Dans l'index, il est géré le défilement qui fait lire ?

**Comment by tontof** [comment]
Oui oui ce comportement existe depuis le début, peut-être même avant tinder
Du coup il fonctionne pareil dans cet index.

**Comment by cborne** [comment]
ah ben je le découvre, il faudra le mentionner alors. 

je pense quand même que pour un comportement similaire, un 0 dans l'url du shaarli devrait virer le bouton.

**Comment by cborne** [comment]
en tout cas la dernière version dans le txt me va bien. Mes doigts boudinés appuient sur conserver, ça passe.

**Comment by tontof** [comment]
Ah ben parfait. J'suis en train de me dire que le défilement ce n'est pas pour lire, c'est pour faire article suivant. Ça le lit uniquement si dans les options, il y a le marquage automatique des articles comme lus.

Sinon l'idée du shaarli à 0 pourrait être une bonne idée pour virer le bouton, mais un user.css en est également une :-)

**Comment by cborne** [comment]
ouais mais moi je veux pas sortir du rang, je veux juste utiliser :D

Néanmoins dans la cohérence du 0 que tu as mis en place, je crois que le 0 pour virer le bouton reste une excellente idée :+1: 

je suis persuadé que tu as envie de faire une nouvelle version. Cela dit à part un flux RSS qui rentrait pas, le problème de la version mobile qui favorisait pas, j'ai un superbe article que je publie sur FreshRSS que je pourrai pourrir le surlendemain pour annoncer mon retour sous KrissFeed.

**Comment by cborne** [comment]
j'attends avec impatience ton projet de page perso facebook sinon

**Comment by tontof** [comment]
Oui mais autant modifier le CSS, c'est vite fait, autant ajouté un comportement différent, ça prend du temps que je n'ai pas trop en ce moment :-)
Surtout que pour la nouvelle version, j'aimerais pouvoir utiliser https://github.com/kriss/mvvm
et comme il reste encore une montagne de code à faire, ce n'est pas pour tout de suite.

Tu devrais avoir des news de https://github.com/tontof/kriss_fbwg avant mais il faudra encore être un peu patient ^^
