### ISSUE TITLE
Marche pas : https://actualite.housseniawriting.com

### ISSUE THREAD

**Issue by cborne** [tontof/kriss_feed#368]
Pour exemple : https://actualite.housseniawriting.com/insolite/feed/

Je tombe avec : Operation timed out after 4001 milliseconds with 0 bytes received

Merci !

**Comment by tontof** [comment]
Ton flux est trop long à répondre. Si tu veux augmenter ton timeout, il te faut créer un répertoire plugins et ajouter un fichier ```.php``` qui contient
```php
<?php
MyTool::$opts['http']['timeout'] = 10;
```
Malheureusement, c'est pour le moment la seule solution et ça modifie le timeout pour tous les flux ce qui peut être problèmatique si tu as beaucoup de flux qui ne répondent pas et qui vont ralentir la mise à jour.

L'autre solution sans passer par KrISS feed est d'utiliser un flux RSS proxy qui répondra plus vite mais sera mis à jour moins souvent.

**Comment by cborne** [comment]
Je confirme que le flux a pu être ajouté, je suppose que je peux jouer sur le timer.
