### ISSUE TITLE
Fatal Error XML 5: Fatal Error XML 5: Extra content at the end of the document

### ISSUE THREAD

**Issue by cborne** [tontof/kriss_feed#369]
Bonjour !

J'ai une erreur sur le flux de l'annonciateur de la mort de Windows phone chaque semaine : http://www.ginjfo.com/feed

Merci

**Comment by tontof** [comment]
C'est balot : https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.ginjfo.com%2Ffeed

**Comment by cborne** [comment]
bon plutôt réactif, il vient de corriger. Comme quoi si on demande pas, on n'a pas

**Comment by tontof** [comment]
Merci à toi de rendre le web meilleur en faisant corriger ces petits détails ;-)

**Comment by cborne** [comment]
c'est important, je sais et c'est ma mission. D'ailleurs j'attends que tu
livres ton nouveau programme :D

tontof <notifications@github.com> a écrit :

> Merci à toi de rendre le web meilleur en faisant corriger ces petits
> détails ;-)
>
>   —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub[1]
>       



Liens:
------
[1] https://github.com/tontof/kriss_feed/issues/369#issuecomment-210602731
