### ISSUE TITLE
KrISS Feed and Php 7

### ISSUE THREAD

**Issue by P3ter** [tontof/kriss_feed#371]
Hi,

Does KrISS Feed support Php 7.0 ? I have the error message below, when I try to update a website feed.

"PHP Fatal error:  Uncaught Error: Call to undefined function mb_internal_encoding() in /var/www/krissfeed/index.php:762" - https://framapic.org/u0p8wMn9HzNZ/IbknhEjt7Cis.png

**Comment by tontof** [comment]
I did not have PHP 7.0 to test but on PHP doc it's seems to be OK:
http://php.net/manual/en/function.mb-internal-encoding.php
Are you sure php-mbstring is installed for PHP 7.0 ?
http://tontof.net/kriss/feed/#requirements

**Comment by P3ter** [comment]
Works after installing php7.0-mbstring.
Thanks :-)
