### ISSUE TITLE
Display player for audio files

### ISSUE THREAD

**Issue by sebastienaubry** [tontof/kriss_feed#372]
For audio files, would it be possible to display a small media player directly inside KrISS feed? It would be great for podcasts.
Thanks

**Comment by tontof** [comment]
I guess, it's possible.
Can you provide me a rss link example ?

**Comment by sebastienaubry** [comment]
Hello,
Any Podcast feed should work. Here is an example: http://radiofrance-podcast.net/podcast09/rss_14007.xml

**Comment by tontof** [comment]
You're lucky I had time to add this !
https://github.com/tontof/kriss_feed/commit/3fc964453c6d6c17aed7056ebd9cc80e23281c28
Enjoy
https://raw.githubusercontent.com/tontof/kriss_feed/master/index.php

**Comment by sebastienaubry** [comment]
Thanks a lot

**Comment by sebastienaubry** [comment]
Hi,
I just tested it, but do not see the player.
![kriss](https://cloud.githubusercontent.com/assets/2082258/16031330/3b4b2dd8-31fa-11e6-825d-06d46ee1ce06.png)

**Comment by tontof** [comment]
It will appear for new feed on update.
If you want to see it for this feed you can delete it and add it again :-)

**Comment by sebastienaubry** [comment]
I tried to delete it and add it again, but still do not see any player on the 13 articles of the feed.
Thanks

**Comment by tontof** [comment]
I've tried on 
http://tontof.net/feed/?currentHash=T3VyIA&view=expanded
and it works.
Do you see the player on my link ?
Maybe it's linked to your browser

**Comment by sebastienaubry** [comment]
No, I don't see it. I'm using Firefox under linux.
When displaying the source I see:

<audio controls><source src="http://rf.proxycast.org/1171694729906102272/14007-05.06.2016-ITEMA_21002286-1.mp3"><a href="http://rf.proxycast.org/1171694729906102272/14007-05.06.2016-ITEMA_21002286-1.mp3">http://rf.proxycast.org/1171694729906102272/14007-05.06.2016-ITEMA_21002286-1.mp3</a></audio>

**Comment by tontof** [comment]
![capture](https://cloud.githubusercontent.com/assets/1648892/16034419/03c5685c-3212-11e6-9b59-a90c75d26ff4.png)
I'm also sing Firefox 46.0 on Linux Mint and it works...
On source you should see something as
```<br><audio controls=""><source src="http://rf.proxycast.org/1174344394057195520/14007-12.06.2016-ITEMA_21007891-1.mp3"></source><a href="http://rf.proxycast.org/1174344394057195520/14007-12.06.2016-ITEMA_21007891-1.mp3">http://rf.proxycast.org/1174344394057195520/14007-12.06.2016-ITEMA_21007891-1.mp3</a></audio>```

**Comment by tontof** [comment]
http://www.w3schools.com/HTML/tryit.asp?filename=tryhtml5_audio_all
Does it works ?

**Comment by tontof** [comment]
On https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats
```The MP3 audio format (.mp3, audio/mpeg; distinct from the above MP3 audio in an MP4 container case) is supported in <audio> by Firefox/Firefox for Android/Firefox OS when the operating system provides an MP3 decoder```
