### ISSUE TITLE
$kfcmaxupdate forced to maxlength="3" in config panel

### ISSUE THREAD

**Issue by mitsukarenai** [tontof/kriss_feed#373]
If I understand correctly, `$kfcmaxupdate` is the maximum amount of minutes KF can delay an update of a feed.
However in the config panel, it's lengh is restricted (and type is text):
`<input type="text" maxlength="3" id="maxUpdate" name="maxUpdate" value="<?php echo $kfcmaxupdate;?>">`
which means the average user can only set a maximum number of 999 minutes (~16 hours). Or..   `K7£` minutes...

In my use case, some feeds are updated once every... 3-4 months ? And near-realtime updates are not useful to me, so I edited `config.php` to manually set a maxUpdate of 15 days:
`$this->maxUpdate = '21600';`

I suggest the following change in the HTML code of the config panel, allowing the user to set arbitrary delay minutes :)
`<input type="number" id="maxUpdate" name="maxUpdate" min="1" value="<?php echo $kfcmaxupdate;?>"> `

**Comment by tontof** [comment]
I guess you are right :-)
https://github.com/tontof/kriss_feed/commit/1ac380bc22c2fd58dbfee4b5cf1813a459d675ef
I think, it's ok now
