### ISSUE TITLE
Ajouter à wallabag

### ISSUE THREAD

**Issue by emporeso2** [tontof/kriss_feed#374]
Bonjour, j'ai une instance wallabag chez framabag.org,
est-ce que dans un avenir plus que proche ;-) unbouton/lien sera ajouté à kriss_feed pour envoyer des articles vers wallabag.

Un gros merci pour kriss_feed que j'utlilise au quotidien avec mes 200 flux,bon obligé de le lancer 3 fois de suite ,à cause de timout sur certain flux,c'est un pur bijouxet pourtant j'en ai testé d'autres rss reader et bien je reviens toujours vers kriss_feed.
Quand je pourrais il faut que fasse un theme ;-)

**Comment by tontof** [comment]
Tu ne peux pas utiliser le bouton share ou tu penses qu'il faut un bouton supplémentaire ?
Parce que je suppose que c'est possible en personnalisant l'url dans les paramètres.
Tu peux personnaliser le timeout: https://github.com/tontof/kriss_feed/issues/267#issuecomment-23675713

**Comment by mwolff44** [comment]
Bonjour,

je suis aussi intéressé par cette fonctionnalité. Par contre, je ne vois pas comment paramétrer le bouton share ?

**Comment by tontof** [comment]
Il suffit d'aller dans la partie configuration et sur l'option Shaarli URL
Il faut entrer le lien du bookmarklet de wallabag.
```
http://votre-url-de-wallabag/bookmarklet?url=${url}
```
Ensuite quand vous cliquez sur share/partager ou que vous appuyez sur la touche 's' ça devrait vous ouvrir une fenêtre pour que vous puissiez ajouter l'article sur votre wallabag.

**Comment by emporeso2** [comment]
J'ai essayé mais il y a un probleme d'encodage d'url : 

`https://www.framabag.org/u/xxx/?action=add&autoclose=true&url=http%3A%2F%2Funeheuredepeine.blogspot.com%2F2016%2F08%2Fla-sociologie-comme-elle-se-lit.html`

Si tu as une explication la dessus ca m'interesse.

Je suis peut etre trop demandeur ! mais je vois une difference en partager un lien via share sur shaarli par exemple et sauver un article via un bouton hypothetique save qui renvoit vers son wallabag ?

Chez la communauté shaarli ils ont un plugin : `https://github.com/shaarli/Shaarli/tree/master/plugins/wallabag`

**Comment by tontof** [comment]
C'est bizarre mais j'ai testé sur la démo de wallabag et ça fonctionne.
Tu peux tester ici:
http://tontof.net/feed/?currentHash=IczCNA
J'ai mis:
http://v2.wallabag.org/bookmarklet?url=${url}
dans la config
Et quand je clique sur share ça fonctionne
C'est wallabag/wallabag pour login/mdp

Par contre ça ne fonctionne sur les pages web.

**Comment by emporeso2** [comment]
Je viens de refaire un test ca fontion tres bien chez wallaba.org mais pas framabag.org.
Tip top ca fonctionne merci.

**Comment by tontof** [comment]
Euh, du coup si ça fonctionne sur wallabag et pas framabag ça fonctionne pas complètement si ?
Les comptes sont communs entre les 2 ?

**Comment by emporeso2** [comment]
Non c'est 2 wallabag diffrent , chez framabag c'est une v1 de walabag.

**Comment by tontof** [comment]
Ah ben faut regarder dans les options de la v1, l'url est effectivement différente.
J'ai pris l'url dans le bookmarklet « bag it! »
Il doit y avoir un équivalent, mais je n'ai pas trouvé de démo sur framabag.

**Comment by emporeso2** [comment]
Moi aussi j'ai pris le bagit de framabag avec ceci :
https://www.framabag.org/u/xxxx/?action=add&autoclose=true&url=${url}

L'url est mal encodé justement ?

**Comment by tontof** [comment]
Peut-être qu'il y avait effectivement un problème sur la v1 parce que les url ne peuvent pas être passées directement dans une url et il faut les encoder avant.
C'est pour ça qu'il y a ```encodeURI(url)``` sur le bookmarklet de la v2
S'il n'y a pas ça dans la v1, ça explique le problème.

Je n'ai pas de vraies propositions à proposer sauf si tu veux quand même que ça marche pour framabag, je pense qu'en supprimant ```encodeURIComponent```
https://github.com/tontof/kriss_feed/blob/master/index.php#L6618
ça devrait fonctionner (si tu utilises la partie javascript de kriss feed
sinon ça doit être ```urlencode``` qu'il faut supprimer
https://github.com/tontof/kriss_feed/blob/master/index.php#L9177

Peut-être que c'est aussi lié à l'utilisation de ```encodeURIComponent``` et pas ```encodeURI``` mais je pense pas
http://stackoverflow.com/questions/4540753/should-i-use-encodeuri-or-encodeuricomponent-for-encoding-urls

**Comment by emporeso2** [comment]
Dans le coup je trouve la v2 de chez wallabag mieux foutu je suis passé chez eux .
Effectivement a default je pense que c'est la v1 qui pose probleme.

**Comment by mwolff44** [comment]
sur le site de wallabag, il ne te propose de t'enregistrer que sur framabag, le site http://v2.wallabag.org/login ne me semble être là que pour la démo.
La question est : quand framabag migrera en v2 ?

**Comment by emporeso2** [comment]
Les 2 services sont séparés ,  l'inscription se fait ici sans soucis : http://v2.wallabag.org/register/

**Comment by emporeso2** [comment]
@mwolff44 ou a tu lu que http://v2.wallabag.org/login est une demo ?

**Comment by marienfressinaud** [comment]
Pour la v1 de wallabag, il faut faire un `base64_encode` de l'URL. @tontof si jamais on te demande de supporter d'autres services tu peux te baser sur ce fichier de FreshRSS : https://github.com/FreshRSS/FreshRSS/blob/master/data/shares.php, ça peut dépanner si tu as un doute :).

Pour ce qui est de la migration de Framabag vers la v2, ça va se faire mais pas forcément immédiatement. Le problème c'est qu'il faut migrer les comptes de la v1 vers la v2, ce qui prend du temps et est un peu compliqué.

**Comment by tontof** [comment]
Bien sympa le lien avec les différentes configs.
Le problème c'est qu'avec KrISS feed ce n'était pas prévu de pouvoir appliquer des fonctions sur l'url.
Il va donc falloir attendre une prochaine version... ou modifier directement le code à la main dans le fichier pour ceux qui en ont besoin.
