### ISSUE TITLE
feed items not marked as read when i switch to the next

### ISSUE THREAD

**Issue by bennap** [tontof/kriss_feed#376]
Hi,
I've just noticed this bug today. I have updated my kriss_feed version from 8.4 yesterday to the last.
I have choose to mark as reas an item when i switch to the next (not all of the page, just item) but it doesn't work. I need to push read button on each item or the mark all of the page as read.
I tried to debug javascript, but I have seen nothing.
This bug wasn't happen on only feed but on all.

**Comment by tontof** [comment]
Sorry I can not reproduce the bug. I've just updated to the last version and when I push 'N' key or if I click on 'next' button it marks correctly as read the item.
Tell me more precisely how you do.
You can try on demo: http://tontof.net/feed
- login : tontof
- password : krissdemo

**Comment by bennap** [comment]
Sorry i thought it also works when i click on the next item without 'next' button.

**Comment by tontof** [comment]
No problem !
