### ISSUE TITLE
Wrong Token error on windows phone 8.1 login

### ISSUE THREAD

**Issue by a-Name** [tontof/kriss_feed#378]
Hi, 

I have installed Kriss Feed on my personal server a little while ago and now I have this new windows phone from which I am unable to connect to my Kriss Feed instance.
"Wrong token" is displayed every time I try to connect no matter which browser I try to connect with.
I already tried with IE, UC Browser, Opera, and Surfy Browser.
It works perfectly on computer desktops, usually using Firefox but never had this issue before.

Thanks for your help! :)

**Comment by tontof** [comment]
Wow sorry I've completely missed your issue. I hope you've found a solution...
