### ISSUE TITLE
undo last action button

### ISSUE THREAD

**Issue by Nono-m0le** [tontof/kriss_feed#379]
Serait-il possible d'ajouter un bouton 'undo last action', car encore une fois, j'ai marqué tous mes flux en "lu", sans trop savoir comment d'ailleurs...

Et dans ce cas précis, avec quelques flux toujours en "non lu" depuis qq semaines/mois sont tout simplement introuvable désormais !

**Comment by tontof** [comment]
Désolé, mais c'est une action bien trop compliquée à mettre en place. Même si je comprends bien l'idée et le besoin, je ne vois pas comment je pourrais ajouter ça simplement :-(
Cette fonctionnalité me manque aussi parfois quand je marque un article comme lu trop vite. Avant la refonte de KriSS feed (version 5) je gardais un historique dans le navigateur qui me permettait de faire un undo sur les 10 derniers éléments. Mais du coup ce n'est pas global, juste au niveau des articles.

**Comment by Nono-m0le** [comment]
Bon, AGAIN :p 
Serait-il possible de placer un cartouche de confirmation lorsqu'on tente de "marquer tous les éléments en lu" ?

**Comment by tontof** [comment]
En attendant que je regarde pour voir si je peux faire une modif, tu peux peut-être tout simplement supprimer dans le menu la possibilité de marquer comme lu/non lu ?
Comme ça plus de problème lié à tes gros doigts ?

**Comment by Nono-m0le** [comment]
J'ai trouvé !!!

En fait, parfois, l'auto scroll up monte la page tout en haut et affiche donc le compteur total des news.
Quand on clic sur ce nombre total => ca passe tout en lu.

Comment je désactive cette action ?

**Comment by tontof** [comment]
J'suis pas contre une petite capture d'écran pour me montrer de quel nombre total tu parles.
Pour moi il n'y a que sur la liste des flux où il y a un nombre qui marque tous les flux comme lus
206 par ex ici : https://tontof.net/feed/
Mais si c'est ça, je n'ai pas trop compris le rapport avec l'auto scroll up.
Du coup c'est quel action que tu veux désactiver, l'auto scroll up ou le nombre qui marque tous les flux ?

**Comment by Nono-m0le** [comment]
C'est bien le 206 oui. 
J'aimerais enlever le fait de marquer tout comme lu sur ce chiffre (je ne comprends à vrai dire, même pas son intérêt ici !)

**Comment by tontof** [comment]
Sur celui là ou sur tous ? Disons que c'est un raccourci pour effectuer une action sans cliquer sur plein de boutons.
Il m'arrive d'y cliquer dessus quand j'ai beaucoup trop d'articles à lire et que je n'ai pas envie de tout lire. Par contre je ne le fais effectivement pas souvent sur celui là en particulier mais plus sur un dossier de flux ou un flux en particulier.

**Comment by tontof** [comment]
Si tu ajoutes ou modifies ton style.css en ajoutant ça, ça doit marcher:
- Pour le bouton principal sur tous les flux
```css
#all-subscriptions > h4 > a {
     pointer-events: none;
}
```
- pour tous les boutons de la liste marquer comme lu
```css
#all-subscriptions .mark-as {
     pointer-events: none;
}
```

**Comment by Nono-m0le** [comment]
Uniquement celui-là.
Les autres (même si que très rarement) ca m'arrive de les utiliser également.

La, celui est genant car quand on a des micro-lag sur le téléphone (et qu'on fait plusieurs "read" à la suite/rapidement).

Ben, il arrive ce qu'il arrive, à la place de tapper sur "read", c'est sur le "206" que ca tombe et ... plus de flux :D

**Comment by Nono-m0le** [comment]
Normal que je n'ai pas de style.css ? :D (et que j'ai vu passer un this-kfc dans ton code ? :p )

**Comment by tontof** [comment]
https://tontof.net/kriss/feed/#style
Il faut créer un dossier inc qui contient un fichier user.css (pas style.css comme je disais)

Du coup j'suis pas sûr d'avoir compris ton this-kfc .

**Comment by Nono-m0le** [comment]
Dans index.php: 
  41     public function __construct($dataFile, $cacheDir, $kfc)
  42     {
  43         $this->kfc = $kfc;

Merci pour le css, ca semble marcher (j'ai peur de tester sur mon mobile :p)

**Comment by Nono-m0le** [comment]
Bon, il se trouve que ce n'est pas seulement le "206" qui n'est plus "cliquable" mais le "All Feed" également, et celui-là, il m'arrive de l'utiliser :) 
Une solution ?

**Comment by tontof** [comment]
```CSS
#all-subscriptions > h4 > a:first-child {
     pointer-events: none;
}
```
à la place :-)
