### ISSUE TITLE
Install on openbsd

### ISSUE THREAD

**Issue by mwolff44** [tontof/kriss_feed#381]
Hi,

I use successfully krissfeed on debian. But i migrate my server to openbsd, and i try to install on it (openbsd 6 and php7).
Installation seems OK, but i can not update feeds, i obtain : "Couldn't resolve host " 
I have integrated necessary link in httpd jail.

Is someone have installed it on opendsb ? is here anything special to do ?

Thanks

**Comment by mwolff44** [comment]
Issue resolved

**Comment by tontof** [comment]
Great! I had no idea.
Did you do something that may be useful for some other people ?

**Comment by mwolff44** [comment]
an issue between chroot and dns resolver. I used a symbolic linck in place of copying the file. Did you plan to resolve the issue with https feed ? i have added the line in index.php, but i do not like too much this solution.
Thanks for your great job!

**Comment by tontof** [comment]
What did you mean by issue with https feed ?
I have no problem.

**Comment by mwolff44** [comment]
I talk about this : https://github.com/tontof/kriss_feed/issues/370

**Comment by tontof** [comment]
Well, no sorry, I did not look onto that.
I try again the feed https://blog.moutonlibre.net/rss.php
that was posing problem last time and now
it's working.
I guess it's a very limited problem and it depends on 
server configuration. I won't have enough time to dig into
that problem, sorry.

**Comment by mwolff44** [comment]
I agree. Like you, i do not have many free time. But i will have a look later. Thanks for this great app.
