### ISSUE TITLE
Add German translation (file attached)

### ISSUE THREAD

**Issue by pille1842** [tontof/kriss_feed#382]
Hey, I really like KrISS and thought a German translation would be nice. I attached the .po file. Maybe you can include it. (I had to zip it to allow uploading on Github.)

Cheers, Eric
[de.po.zip](https://github.com/tontof/kriss_feed/files/724230/de.po.zip)

**Comment by tontof** [comment]
Thanks a lot, I've just added your translation
https://github.com/tontof/kriss_feed/commit/9d5662db505e83a263feb2f68a987f758d49bae1
and
https://github.com/tontof/kriss_feed/commit/cc4ee2e6429642a3d376caedd41f5505024af570
A preview here: https://tontof.net/feed/?lang=de
