### ISSUE TITLE
plugin youtube ?

### ISSUE THREAD

**Issue by Nono-m0le** [tontof/kriss_feed#384]
Je viens de découvrir le plugin FreshRSS-Youtube et je suis assez jalou !

Serait-ce envisageable de pouvoir voir les videos youtude directement depuis KrissFeed ?
Ca serait juste ... merveilleux :)

**Comment by tontof** [comment]
Rhô j'espère que tu parles bien d'une page d'un flux de youtube
Du style http://www.youtube.com/feeds/videos.xml?channel_id=UCFAwg9-oAwpAoBIVj3C3v_w
Si oui alors oui
https://raw.githubusercontent.com/tontof/kriss_feed/master/src/index.php
Depuis le temps que je m'étais dit que ce serait bien de le fait ^^
https://github.com/tontof/kriss_feed/commit/4ffaac55fdb0fb01bb8f73f95151eeec1d7c470c

**Comment by Nono-m0le** [comment]
Ben, l'idée, c'est de pouvoir voir la video directement dans krissfeed, mais oui je parle bien de ce type de lien !
J'utilise pour ma part les deux formats : http://www.youtube.com/feeds/videos.xml?user=Palmashow
ou http://www.youtube.com/feeds/videos.xml?channel_id=UCJHA_jMfCvEnv-3kRjTCQXw
Si c'est bien ce que tu as fait, ca ne fonctionne pas chez moi :D ou alors j'ai un problème de cache ... ou il faut supprimer quelques chose quand on MAJ ?

**Comment by tontof** [comment]
Ah ben oui par contre c'est que pour les nouveaux arrivés.
Essaye en supprimant le flux et en l'ajoutant !

**Comment by Nono-m0le** [comment]
Tu l'as compris, ça a fini par fonctionner... Mais ! 

J'utilise Firefox sur mon Android et depuis, chaque page avec un lien YouTube dedans me telecharge un fichier ! 
Avant d'ouvrir un nouveau bug, est-ce que tu pourrais me dire si tu as le même comportement ?

**Comment by Nono-m0le** [comment]
Firefox v 53.0.2 et le fichier téléchargé est du nom (sans extension) de la partie après le https://m.youtube.com/watch?v= 
Ex pour la vidéo https://m.youtube.com/watch?v=XX3jzTYJNhc, le fichier se nomme XX3jzTYJNhc

**Comment by tontof** [comment]
Ah ben bravo, il fallait me le dire avant la version 8.7 !
J'ai corrigé dans la version de développement dans le dossier src.

**Comment by Nono-m0le** [comment]
Marche toujours pas chez moi !

**Comment by tontof** [comment]
Avec de nouvelles vidéos ? Pas des anciennes ?
Parce que chez moi ça marchait bien.
Il s'agit bien de la dev : https://raw.githubusercontent.com/tontof/kriss_feed/master/src/index.php ?

**Comment by Nono-m0le** [comment]
autant pour moi .... J'ai vraiment du mal à retenir le fait que ca s'applique au NOUVEAU flux/article !
=> Ca fonctionne ! (et désolé pour la version 8.7 :p)

**Comment by tontof** [comment]
Cool !
Pas de soucis ;-)
