### ISSUE TITLE
Installation problem and getUrl()

### ISSUE THREAD

**Issue by gitfry** [tontof/kriss_feed#386]
Hello,

I've installed Kriss on OpenBSD, using relayd as a TLS accelerator, and httpd as web server.
I finally manage to make Kriss work, but since I'm a PHP noob, I'm not sure I did it right because I modified the code (usually, bad things start this way).

Long story short : in order to make it works, getUrl() returns $scriptname only.

Here is the long story :

Internet --->http port on relayd ---> port 5080 on httpd (with 301 https redirection)
Internet --->https port on relayd---> port 5443 on httpd 

Relayd is a tls server, not a client for 2nd case.

(On the same server, I run Shaarli with a quite common and comparable configuration, and it works perfectly. I mention it since you made reference to it in other issues.)

What went went wrong with Kriss ? I landed on the installation page (but whithout css, like issue #339), typed login and password, hit enter, and then I was stuck with the login page, whatever I did (perhaps there is a confirmation page somewhere between, but I forgot). The data/config.php file was normally created.

I noticed that when the connexion timed out, url in browser was something like :
`https://my.domai.ne:5443/?bla` and my firewall confirmed the blocked connexion to 5443 port.

More, when I tried to use Kriss with httpd on port 80 (no relayd), everything went ok, and httpd logs showed me requests like :

> GET /? HTTP/1.1

followed by

> GET /?file=style.css%26version=8.7 HTTP/1.1

the last one I never saw with my initial configuration.

I desperately tried to change httpd and relayd configuration. Ended up with nothing. Looking at the code, I noticed the getUrl() function. I maybe wrong as I do not consider myself competent for this, but I'm not sure Kriss should manage port, protocol or server name. Tweaking this function, I ended up with a getUrl() that just return $scriptname.

I wouldn't say everything works like a charm, but it seems Kriss survived the surgery, and I can go beyond login page, which is a beginning.

Since I'm not sure how stupid my modification is, I would appreciate any other opinion.

Thanks - a lot - for Kriss,

Have a nice day.

**Comment by tontof** [comment]
I did not understand all your config stuff, but if you've just modified the getUrl function, I guess you can handle this without modifying KrISS feed.
You can create a plugins directory and put a php file using the BASE_URL parameter as explain here:
https://github.com/tontof/kriss_feed/issues/241#issuecomment-23611458
I don't know exactly what value you will have to set, but it should do the trick ?

**Comment by gitfry** [comment]
Perfect for me, sorry I didn't notice it before.

My plugins/base.php file : 

```
<?php
$GLOBALS['BASE_URL'] = 'https://my.domai.ne';
?>
```

Thanks again for KrISS feed.

**Comment by tontof** [comment]
Great!
