### ISSUE TITLE
video en overlay

### ISSUE THREAD

**Issue by Nono-m0le** [tontof/kriss_feed#388]
Hello,

Alors, juste pour vérifier que ce ne soit pas un problème de mobile / OS / Flux.

Sur mon mobile (HTC 10), avec Firefox Mobile (à jour) quand j'affiche dans mon flux cet article : http://mashable.com/2017/08/16/13-reasons-why-season-2-details j'ai d'une part une sympathique video en auto-play (que je conchie au plus haut point) mais en plus ... je suis complètement bloqué dans ma navigation => Pas de moyen de fermer la video (overlay) !!

Suis-je le seul ? Je n'ai pas ce comportement dans firefox 'desktop'.

**Comment by tontof** [comment]
Salut,

J'arrive à reproduire, mais en appuyant sur le menu retour d'Android, j'arrive à fermer la vidéo.
Comme le code n'est pas filtré, le javascript est exécuté et c'est ce qui doit faire que la vidéo fasse de l'autoplay. Mais pour le coup, je pense qu'effectivement c'est un peu la faute du flux qui fait de la merde :-)

**Comment by Nono-m0le** [comment]
Ah oui, la touche retour fonctionne :) Merci du feedback :)

----- Message de réponse -----
De : "tontof" <notifications@github.com>
Pour : "tontof/kriss_feed" <kriss_feed@noreply.github.com>
Cc : "Nono" <nono@m0le.net>, "Author" <author@noreply.github.com>
Objet : [tontof/kriss_feed] video en overlay (#388)
Date : mer., août 16, 2017 20:54

Salut,
J'arrive à reproduire, mais en appuyant sur le menu retour d'Android, j'arrive à fermer la vidéo.

Comme le code n'est pas filtré, le javascript est exécuté et c'est ce qui doit faire que la vidéo fasse de l'autoplay. Mais pour le coup, je pense qu'effectivement c'est un peu la faute du flux qui fait de la merde :-)

&mdash;You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
