### ISSUE TITLE
Lancement d'un telechargement 

### ISSUE THREAD

**Issue by emporeso2** [tontof/kriss_feed#390]
Bonjour,
ayant la derniere mise à jour la 8.7, au lancement de mon kriss feed j'ai un telechargmeent d'un fichier flash qui se lance ? etant abonée au flux rss de chaines youtube , ce comportement est nouveau !

**Comment by tontof** [comment]
Bonjour,

Je suis surpris d'un tel comportement parce que je suis également abonné à des flux RSS de chaines youtube et je n'ai pas ça. (Tu peux isoler un exemple et m'envoyer un lien pour tester ?)
C'est sur un ordi ou mobile ?

**Comment by emporeso2** [comment]
Pas reussi a reproduire mon bug,je pense que ca venais de firefox nightly sur pc et mobile !
