### ISSUE TITLE
Changement de theme

### ISSUE THREAD

**Issue by emporeso2** [tontof/kriss_feed#392]
Depuis la version 8.7, lorsque je met un nouveau theme user.css dans /mon_kriss_feed/src/inc/ et rien ne se passe ?

**Comment by tontof** [comment]
Normalement, il n'y a pas le dossier ```src```
http://tontof.net/kriss/feed/#css-user

**Comment by emporeso2** [comment]
Oups erreur de ma part, j'ai tapé sur mon clavier trop vite ;-)
