### ISSUE TITLE
bouton force update

### ISSUE THREAD

**Issue by emporeso2** [tontof/kriss_feed#393]
Etant un feneant et utilisant de plus en plus ma tablette et telephone,losque j'update mes flux(200) et qu'il y a des erreurs je relance un force update , hors je me dois scroller mes 200 flux pour aller en bas de page ! 
Ca aurait ete pratique d avoir les infos et les boutons de bas de page en haut de page aussi ?

**Comment by tontof** [comment]
I've added buttons on top
https://github.com/tontof/kriss_feed/commit/b7d70833599ecd5e7d8338d288539b106bf0384c
You will have to download the src version
https://raw.githubusercontent.com/tontof/kriss_feed/master/src/index.php

**Comment by emporeso2** [comment]
Un grand merci tontof pour ta reactivité et ton travail.
Kriss feed declasse de loin tous les autres outils que j'ai essayé.
Encore bravo.
