### ISSUE TITLE
Hide feeds by default from "All Feeds" view?

### ISSUE THREAD

**Issue by poVoq** [tontof/kriss_feed#399]
Would be nice if there was a per feed option in the "Edit feed" configuration to exclude it from the main listing and only have it accessible from the left hand menu?

Purpose: I have a high volume feed (job offers) that I would like to check easily in the same interface from time to time, but otherwise really fills up my daily reading list.

Thanks!

Edit: a similar functionality in the "Edit Folder" configuration would be awesome as well.

**Comment by tontof** [comment]
I understand the idea, but that's also a too specific case to integrate directly into KrISS feed (and also too complicate to add easily). For that kind of thing I suggest too use 2 instance of KrISS feed with one specific for job offers that update automatically using the cron option.

**Comment by poVoq** [comment]
Ok, that is a bit unfortunate, but thanks for explaining the difficulty in actually implementing it.

**Comment by fpunktk** [comment]
If I understand it correctly, then a simple solution might be to put the regular feeds (all except the ones that should not be listed in "All Feeds") in a "daily reading" folder. "job offers" go in a different folder. Then use "daily reading" instead of "All Feeds". 
Does it make sense?

**Comment by poVoq** [comment]
Yeah, makes sense, but then I can't have any sub-categories for my daily reading and the default view would still render all the links. Still, good idea, I hadn't really thought about that.
