### ISSUE TITLE
erreur ajout flux

### ISSUE THREAD

**Issue by emporeso2** [tontof/kriss_feed#409]
Bonjour, 

lors de l'ajout de ce flux : http://lessoustitresdelahonte.tumblr.com/rss j'ai cette erreur : 
Fatal Error XML 5: Fatal Error XML 5: Extra content at the end of the document

Merci pour kirss_feed.

**Comment by tontof** [comment]
Salut,
Depuis qu'il y a le RGPD, il n'est plus possible d'utiliser les flux RSS sur tumbr. En cliquant sur ton lien je tombe sur :
```
Avant de continuer, quelques nouvelles de notre part
Tumblr fait désormais partie de la famille Oath. Veuillez consulter les nouvelles Conditions Générales d’Utilisation et la nouvelle Politique relative à la vie privée européenne de Tumblr...
```
Et KrISS feed tombe sur la même page d'où le problème de format XML comme c'est en fait du HTML.
Je ne crois pas qu'il existe une solution simple pour accepter les flux RSS Tumblr depuis le RFPD.

**Comment by tontof** [comment]
En cherchant un peu, je suis tombé sur ça :
https://discourse.tt-rss.org/t/change-on-tumblr-rss-feeds-not-working/1158/124
Si tu modifies le user-agent par :
```facebookexternalhit/1.0 (+http://www.facebook.com/externalhit_uatext.php)```
Ça devrait fonctionner. Par contre il faut le modifier globalement pour tous les flux.
En créant un dossier plugins et en ajoutant un fichier contenant :
```
MyTool::$opts['http']['user_agent'] = "facebookexternalhit/1.0 (+http://www.facebook.com/externalhit_uatext.php)"
```
Ça devrait fonctionner

**Comment by emporeso2** [comment]
Que dire geniale , superbe , ca marche tres bien , bravo encore , Kriss_feed est une tuerie ;-)

Encore un tres gros merci.

**Comment by tontof** [comment]
Cool, par contre ça peut ne plus fonctionner du jour au lendemain !

**Comment by emporeso2** [comment]
No soucy ;-)

Merci
