### ISSUE TITLE
Opération "clonage" en rade...

### ISSUE THREAD

**Issue by fpp-gh** [tontof/kriss_feed#412]
Hello, encore merci pour Kriss feed (et pour Bozon :-)

J'ai une instance 8.7 qui tourne depuis des lustres sur un vieux vps OVH, et c'est une vraie drogue, peux plus m'en passer...

Là je suis en train d'essayer de transférer mes "assets" sur une VM Scaleway un peu plus moderne, et je galère avec Kriss !
D'abord j'ai voulu tricher en copiant brutalement le dossier de l'une à l'autre, mais la nouvelle restait vide (sans doute parce les deux "cron" tournaient en même temps avec le même ID ?...).

Du coup j'ai appliqué la consigne officielle pour l'installation depuis zéro : le dossier vide, index.php, et hop...
...sauf que ça marche pas non plus :-(
D'abord, quand je vais dans "configuration" pour importer mon OPML, j'ai ça qui s'affiche (4 fois) au-dessus de la boîte de dialogue d'import:
_"Notice: A non well formed numeric value encountered in /var/www/kif/index.php on line 4034"_

Ensuite quand j'uploade le fichier OPML (qui tourne sur l'ancienne instance), ça plante :
**Fatal error: Uncaught Error: Class 'DOMDocument' not found in /var/www/monbo.ga/root/kif/index.php:4126
Stack trace: 
#0 /var/www/kif/index.php(8661): Opml::importOpml(Array) 
#1 {main} thrown in /var/www/kif/index.php on line 4126**

Comme je ne pane rien au PHP je ne vois pas où est le problème.
Peut-être le fait d'être passé brutalement d'un PHP 5.5 à un 7.2 ?...

D'avance merci,
FP

**Comment by tontof** [comment]
Salut,
Bozon ce n'est pas de moi, c'est [broncowdd](https://github.com/broncowdd/BoZoN) :-)
Pour ton erreur Class DOMDocument not found c'est parce qu'il faut installer php-xml (php7-xml ou php7.2-xml)
Il faut aussi php-mbstring
http://tontof.net/kriss/feed/#requirements
Je pense que c'est lié à ça, en tout cas j'espère parce que sinon je ne vois pas trop.

**Comment by fpp-gh** [comment]
Oui merci, en fait j'avais réalisé entretemps, en relisant la doc, que j'avais zappé la plupart des "prérequis", l'admin-sys pendant les fêtes c'est pas une bonne idée :-)

Donc maintenant mes feeds OPML sont importés sans problème (même si j'ai toujours les 4 warnings à l'ouverture de la page).

Ensuite j'ai eu un souci de copier/coller de l'URL dans le crontab, qui m'a échappé pendant un bon moment, mais là tout de suite ça roule :-)

Encore merci et bonne année !
fp
