### ISSUE TITLE
No more feeds's updates

### ISSUE THREAD

**Issue by djizuss** [tontof/kriss_feed#417]
It look like that Debian have depreciated php5-curl that is used by Krissfeed to update feeds

**Comment by tontof** [comment]
Can you update to PHP7 ? PHP5 is deprecated:
https://www.php.net/supported-versions.php
Maybe you can try to uninstall php5-curl as KrISS feed can use fopen instead if it does not find curl

**Comment by djizuss** [comment]
So: it was just that php was updated from 5 to 7, but php5-curl was still running
A reboot was the solution :) 
i'm sorry for that and I thank you

**Comment by tontof** [comment]
No problem
