### ISSUE TITLE
Flux rss tronqué

### ISSUE THREAD

**Issue by caywin25** [tontof/kriss_feed#418]
Bonjour, 

Tout d'abord, bravo pour votre travail tontof.
La plupart des flux RSS sont tronqué aujourd'hui quand nous les récupérons.

Y aurait-il une possibilité d'ajouter un bouton qui permettent de récupérer l'article en question en entier dans kriss feed pour le lire dans kriss feed et ne pas aller sur le site ?

Ce serait top.
Merci beaucoup

**Comment by tontof** [comment]
Bonjour,

Désolé pour cette réponse tardive, je n'avais pas reçu ton message. Malheureusement ce n'est pas réalisable facilement et le plus simple est d'utiliser un outil externe qui va chercher le flux complet directement à ajouter dans KrISS feed par exemple avec RSS bridge ou autre : https://wpmayor.com/convert-partial-rss-feeds-full-text/

**Comment by caywin25** [comment]
Ok merci :)
