### ISSUE TITLE
two errors unresolvable following a disk full

### ISSUE THREAD

**Issue by Nono-m0le** [tontof/kriss_feed#421]
Just happened to me ...
My disk was full, so my RSS was throwing those errors:
```
Warning: gzinflate(): data error in /var/www/rss/index.php on line 86

Warning: Invalid argument supplied for foreach() in /var/www/rss/index.php on line 498

Warning: Invalid argument supplied for foreach() in /var/www/rss/index.php on line 150
```

I kept the old directory (with data + sessions), but I had to recreate a folder from scratch (using my feeds.opml + config.php).
Any change to go back to my "working" version ?

**Comment by tontof** [comment]
Arf I guess it depends on where the data.php file was truncated. If it's nearly the end of the file I may be able to fix it by opening it using https://github.com/tontof/kriss_feed/blob/master/src/bin/readData.php and correct it manually (with a little loss of information).
If you want me to look at the your file you can send it to my free address. I should have time on monday next week to look at it!
Sorry for that.

**Comment by Nono-m0le** [comment]
that's quite easy : the data.php is empty ...
I guess it's not recoverable ?

**Comment by tontof** [comment]
Indeed, I can not do anything with an empty file
