### ISSUE TITLE
Security patch required

### ISSUE THREAD

**Issue by d-faure** [tontof/kriss_feed#422]
According to https://phpsecurity.readthedocs.io/en/latest/Injection-Attacks.html#xml-injection

There's a need of some security patches here:
https://github.com/tontof/kriss_feed/blob/d44afdd54baed5af7e690b65295a45579f6b0a48/src/class/Rss.php#L288

and here:
https://github.com/tontof/kriss_feed/blob/d44afdd54baed5af7e690b65295a45579f6b0a48/src/class/Opml.php#L24

No?

**Comment by tontof** [comment]
I guess you're right, I've merged your modif. Thanks!
