### ISSUE TITLE
Update does not retrieve all articles

### ISSUE THREAD

**Issue by doc75** [tontof/kriss_feed#426]
J'ai remarqué récemment que certains flux n'étaient plus mis à jour en mode d'update normal et qu'il fallait que je force la mise à jour.
Je soupçonne que ce changement de comportement récent est lié au dernier commit qui modifie le code de gestion des headers curl (je me demande si avec cette modif les headers ne sont pas envoyés dans tous les cas, même s'ils sont vide alors qu'avant ils n'étaient envoyé que dans un cas précis).

Voici les tests que j'ai fait:

**Version 8.11**:
- Mise à jour (sans force update): **54** nouveaux articles récupérés (la mise à jour mentionne **81** succès et **41** erreurs qui sont principalement ce message d'erreur`Fatal Error XML 74: Fatal Error XML 74: EndTag: '`)
- Mise à jour (avec force update): **55** nouveaux articles récupérés (la mise à jour mentionne **125** succès et **5** erreurs qui sont principalement des sites non accessibles et un seul `Fatal Error XML 74: Fatal Error XML 74: EndTag: '`)

**Version 8.12**:
- Mise à jour (sans force update): **29** nouveaux articles récupérés (la mise à jour mentionne **47** succès et **83** erreurs qui sont principalement ce message d'erreur`Fatal Error XML 74: Fatal Error XML 74: EndTag: '`)
- Mise à jour (avec force update): **60** nouveaux articles récupérés (la mise à jour mentionne **125** succès et **5** erreurs qui sont principalement des sites non accessibles et un seul `Fatal Error XML 74: Fatal Error XML 74: EndTag: '`)

La différence de nombre d'article après le force update entre les tests 8.11 et 8.12 est lié au fait qu'il y a de nouveau articles dans certains feeds.

je soupçonne que le code suivant dans la fonction `loadUrl` envoie toujours le header en 8.12 alors qu'en 8.11 elle ne l'envoyait que si on était passé avant dans `initFeedCache`:

```php
    if (!empty($opts['http']['headers'])) {
        curl_setopt($ch, CURLOPT_HTTPHEADER, $opts['http']['headers']);
```

Est-il possible de revenir en arrière ou de s'assurer que les headers ne sont pas envoyés s'ils ne sont pas settés ?

Désolé si mon analyse est erronée ou incomplète, je ne suis pas un spécialiste PHP.

**Comment by tontof** [comment]
Je pense que c'était lié à ce test : https://github.com/tontof/kriss_feed/blob/0b4cb3869492bb679b05d50669763263d806af3a/src/class/MyTool.php#L48
Comme l'initialisation de l'option http était faite dans la classe ```MyTool``` le test était toujours vrai (d'ailleurs j'aurais peut-être dû l'enlever) mais ça modifiait donc les valeurs pour timeout et useragent.
Est-que la version 8.13 corrige le problème ? Est-ce que les 4 tests ont bien été réalisés à partir d'une même copie originale ?

**Comment by doc75** [comment]
@tontof je fais le test ce soir ou demain pour voir si la 8.13 corrige le souci.
Pour les tests, j'ai fait l'update puis l'update en mode force sans revenir sur le même jeu de donnée. Par contre entre le test avec la 8.11 et la 8.12, j'ai démarrer sur un restore du même backup.

**Comment by doc75** [comment]
@tontof unfortunately version 8.13 does not solve the issue.

Here are the 3 versions tested (starting from the same backup restored, only the `index.php` is different)

**normal update with version 8.11**:
- **123** success
- **8** errors (some feeds not anymore active)
- **102** articles retrieved

**normal update with version 8.12**:
- **46** success
- **85** errors (some feeds not anymore active)
- **60** articles retrieved

**normal update with v8.13**:
- **46** success
- **85** errors (some feeds not anymore active)
- **60** articles retrieved

**Comment by tontof** [comment]
Wow, je n'ai aucune idée mais j'arrive à reproduire le problème je vais donc pouvoir étudier pour trouver une solution.

**Comment by tontof** [comment]
C'est normalement corrigé avec la version 8.14 : https://github.com/tontof/kriss_feed/commit/7f526db44ff8470a22e7007d0ccf8643c080618b

**Comment by doc75** [comment]
@tontof Merci beaucoup pour le fix rapide. Je confirme que le dernier commit permet de retrouver la situation que l'on avait avec la versoin 8.11.

Fixed with https://github.com/tontof/kriss_feed/commit/7f526db44ff8470a22e7007d0ccf8643c080618b (v 8.14)
