### ISSUE TITLE
Stay signed in

### ISSUE THREAD

**Issue by XinHong** [tontof/kriss_feed#427]
Hello,
I would like to remove the login page as I'm using it on local network.

I've followed the FAQ "How to stay signed in ?" but I have errors on login page and I can't login anymore:

Warning: session_start(): open(/var/www//sessions/sess_fj9jevhaq7ahsjdc1kmhtrsvkn, O_RDWR) failed: No such file or directory (2) in /var/www/kriss/index.php on line 4977
Warning: session_start(): Failed to read session data: files (path: /var/www//sessions) in /var/www/kriss/index.php on line 4977

I think the problem might come from the "//" in the cookie file path but I don't know php programing to investigate.

**Comment by tontof** [comment]
Hi,
I guess you can just configure your KrISS feed as public instead of private ?
Just recopy the original index.php and go to configuration page to change the "KrISS feed visibility" to public.

**Comment by XinHong** [comment]
Perfect, thanks :)
