### ISSUE TITLE
Notice: Trying to access array offset on value of type int in index.php on line 602

### ISSUE THREAD

**Issue by Arrappathor** [tontof/kriss_feed#430]
Hi all,

after upgrading to RaspberryPiOS 11.1 Bullseye and PHP 7.4 KrissFeed 8.14 shows in Favorites

`Notice: Trying to access array offset on value of type int in ///index.php on line 602`

on every item. Also no text is shown, the itmes can't be marked als read/unread/no-favorite

![Screenshot_2021-11-17 Favoriten - Kriss feed (12)](https://user-images.githubusercontent.com/17974573/142231233-2ff703e9-fe17-45c1-8599-fc41c8addd70.png)

Beside this, everything seems to be working fine. 
Thanks for all your efforts!

**Comment by tontof** [comment]
Can you try the dev version : https://github.com/tontof/kriss_feed/raw/master/src/index.php
I hope you have a backup in case of problem. I don't know exactly why this happen but the management of favorites is not very good and maybe there is a problem in the saved array that will need to reset starred items :(
Let me know.

**Comment by Arrappathor** [comment]
I have a backup, no problem.
First i tried 8.11 (last stable; same notice) and now i have already installed the dev-version (which calls itself 8.14).
Thanks for your fast reply!

**Comment by tontof** [comment]
I forgot but I did not update the version 8.14, but the last dev has a recent update (last hour).
Did you try since my last message ?

**Comment by Arrappathor** [comment]
I did right now. (It still calls itself 8.14)
But no changes, same notice, sorry.

**Comment by Arrappathor** [comment]
Now it's line 601. ;-)

**Comment by tontof** [comment]
Try the new 8.15 dev, it should be OK now

**Comment by Arrappathor** [comment]
I'd close this issue.
