### ISSUE TITLE
Compatibilité php 8.1

### ISSUE THREAD

**Issue by cyrilst** [tontof/kriss_feed#433]
Bonjour,

je viens de tester KrissFeed 8.17 en php 8.1, et il y a des erreurs à propos de strftime (qui est deprecated à partir de php 8.1).
En désactivant l'affichage des erreurs, KrissFeed a l'air de bien fonctionner.

**Comment by tontof** [comment]
Merci pour l'info, j'ai fait une modif pour remplacer ```strftime``` par ```date```
Tu peux tester avec la version : https://raw.githubusercontent.com/tontof/kriss_feed/master/src/index.php

**Comment by cyrilst** [comment]
Merci pour la correction éclair. Ça fonctionne bien. Je te tiendrai au courant si je vois d'autres erreurs.
