### ISSUE TITLE
Fatal error Uncaught TypeError

### ISSUE THREAD

**Issue by franck-tomek** [tontof/kriss_feed#436]
`Warning: gzinflate(): data error in /xxx/feed/index.php on line 86

Warning: Trying to access array offset on value of type bool in /xxx/feed/index.php on line 475

Fatal error: Uncaught TypeError: array_keys(): Argument #1 ($array) must be of type array, null given in /xxx/feed/index.php:9291 Stack trace: #0 /xxx/feed/index.php(9291): array_keys() #1 {main} thrown in /xxx/feed/index.php on line 9291`

Depuis 2 jours, j'ai cette erreur… rien n'a été changé de particulier sur l'hébergement, je suis juste passé en PHP 8 il y a quelques semaines. Une idée d'où ça peut venir ?

J'ai la dernière version en date depuis plusieurs mois, 8.19.

**Comment by jerrywham** [comment]
Si ce n'est pas un changement, c'est quoi ? Passer à la version de PHP 8 
a des conséquences.

L'erreur dit que la fonction reçoit une valeur nulle alors qu'elle 
attend un tableau.

Dans le fichier kiss_feed/src/index.php ligne 9291, il faut vérifier que 
la variable $listItems existe :

$listHash = (isset($listItems) ? array_keys($listItems) : []);

Je ne sais pas si ça n'entraînera pas d'autres erreurs mais ça devrait 
clôturer celle-là.

Bonne journée.

Jerry Wham

Le 24/11/2022 à 13:53, franck-tomek a écrit :

**Comment by tontof** [comment]
J'ai bien peur que ce soit ton fichier data.php qui est corrompu, tu as accès à un terminal pour tester le fichier avec le script https://github.com/tontof/kriss_feed/blob/master/src/bin/readData.php ? Ou le faire en local en téléchargeant le fichier sur ton ordi.

Si ce n'est pas possible, tu peux en faire une sauvegarde ailleurs et supprimer le fichier puis réimporter les flux à partir de la sauvegarde des opml dans le dossier.

En fonction de la sensibilité des flux je peux aussi jeter un coup d'oeil à ton fichier si tu ne peux pas utiliser le script readData.php.

La corruption peut être liée à plusieurs facteurs liés au serveur. Je n'ai jamais eu de soucis personnellement mais sur certains hébergeurs j'ai eu des retours de problèmes à la sauvegarde du fichier en vas de dépassement de quota par exemple.

**Comment by franck-tomek** [comment]
@tontof Je vais tester tout ça et je te dis. Merci !

**Comment by franck-tomek** [comment]
Et… le opml… aussi. Pas de sauvegarde opml depuis mars 2020. Oups.

**Comment by tontof** [comment]
Oula c'est très bizarre ça, t'es sur un hébergement mutualisé ou perso ? Autant le data vide j'ai déjà entendu mais opml aussi jamais... Désolé.

**Comment by franck-tomek** [comment]
Ah, j'ai des backups sur l'hébergement. Je vais repartir de là, ouf.
C'est un hébergement chez o2switch, je sais pas exactement si c'est mutualisé.

**Comment by tontof** [comment]
Effectivement c'est mutualisé mais j'ai le même hébergeur et je n'ai jamais eu de soucis avec eux.
Et pour le coup ça ne peut pas être lié à un dépassement de quota vu qu'il n'y en a pas.
Désolé, je n'ai aucune idée d'où peut venir le problème.

**Comment by franck-tomek** [comment]
Pas grave, l'essentiel est que j'ai pu récupérer l'opml. Vive les backups !

**Comment by tontof** [comment]
Ouf, merci o2switch !

**Comment by franck-tomek** [comment]
C'est clair ! (j'en suis très content pour ma part)
