### ISSUE TITLE
fix your code (or your site)... :)

### ISSUE THREAD

**Issue by Unixware** [tontof/kriss_feed#439]
http://tontof.net/kriss/feed/ mentions that user styles should be saved as "inc/user.css" but the index.php is actually loading them from "inc/style.css"

thanks

**Comment by tontof** [comment]
The user should indeed used the ```inc/user.css``` file as the ```inc/style.css``` is use for the default KrISS feed style and the code tests the existence of ```inc/style.css``` file for the developpement version in ```src``` directory with ```kriss_feed.php``` file.
If you create a ```inc/style.css``` file, KrISS feed will load it but that's not expected as you will have to redefine all CSS rules where you can only personnalize the ones you want within the ```inc/user.css``` file.

**Comment by Unixware** [comment]
many thanks!!  false alarm and confusion by my side
