### ISSUE TITLE
Fatal Error XML 26: Fatal Error XML 26: Entity 'nbsp' not defined

### ISSUE THREAD

**Issue by max-lg** [tontof/kriss_feed#440]
Updating feed that used to work now fails with above message.

**Comment by tontof** [comment]
I guess the feed returns html code and is not a RSS feed anymore or the server is not allowed to access the url.
Can you provide the feed url and/or check on the validator?
https://validator.w3.org/feed/

**Comment by max-lg** [comment]
"This feed is valid, but interoperability with the widest range of feed readers could be improved ... " ( a few errors) 

The feed is: https://columbiacommunityconnection.com/the-dalles?format=rss

It started working again now. I did save the file that was downloaded from my browser on the day it didn't work. But I'm wondering if, like you said, the web server temporarily returned an HTML error page to the server instead of an RSS feed.
